CashierSystem/Models/Payment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CashierSystem.Models;

public partial class Payment
{
    [NotMapped]
    public string Id { get; set; }

    public Guid PaymentId { get; set; } = Guid.NewGuid();

    public Guid SaleId { get; set; }

    public Guid PaymentTypeId { get; set; }

    public decimal Amount { get; set; }

    public DateTime? PaidAt { get; set; }

    public virtual PaymentType PaymentType { get; set; } = null!;

    public virtual Sale Sale { get; set; } = null!;
}

CashierSystem/Models/PaymentType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CashierSystem.Models;

public partial class PaymentType
{
    [NotMapped]
    public string Id { get; set; }
    public Guid PaymentTypeId { get; set; } = Guid.NewGuid();

    public string TypeName { get; set; } = null!;

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}

CashierSystem/Models/Sale.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CashierSystem.Models;

public partial class Sale
{
    [NotMapped]
    public string Id { get; set; }

    public Guid SaleId { get; set; } = Guid.NewGuid();

    public Guid? CustomerId { get; set; }

    public Guid UserId { get; set; }

    public DateTime? SaleDate { get; set; }

    public decimal TotalAmount { get; set; }

    public decimal? Discount { get; set; }

    public decimal? NetAmount { get; set; }

    public virtual Customer? Customer { get; set; }
    [NotMapped]
    public virtual MyUser? User { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<SaleDetail> SaleDetails { get; set; } = new List<SaleDetail>();
}

CashierSystem/Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CashierSystem.Models;

namespace CashierSystem.Controllers
{
    public class PaymentsController : Controller
    {
        private readonly CashierSystemContext _context;

        private readonly ICustomKeyManager _keyManager;

        public PaymentsController(CashierSystemContext context, ICustomKeyManager keyManager)
        {
            _context = context;
            _keyManager = keyManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var cashierSystemContext =await _context.Payments.Include(p => p.PaymentType).Include(p => p.Sale).ToListAsync();
            
            var k = cashierSystemContext.Select(p =>
            {

                p.Id = _keyManager.Protect(p.PaymentId.ToString());

                return p;

            }).ToList();

            return View(k);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            try
            {
                var k = Guid.Parse(_keyManager.Unprotect(id));

                var payment = await _context.Payments
                    .Include(p => p.PaymentType)
                    .Include(p => p.Sale)
                    .FirstOrDefaultAsync(m => m.PaymentId == k);

                if (payment == null)
                {
                    return NotFound();
                }

                var cashierSystemContext = await _context.Payments.Include(p => p.PaymentType).Include(p => p.Sale).ToListAsync();

                var kh = cashierSystemContext.Select(p =>
                {

                    p.Id = _keyManager.Protect(p.PaymentId.ToString());

                    return p;

                }).ToList();

                return View(payment);
            }
            catch (Exception) 
            {
                return NotFound();
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewData["PaymentTypeId"] = new SelectList(_context.PaymentTypes, "PaymentTypeId", "TypeName");
            ViewData["SaleId"] = new SelectList(_context.Sales, "SaleId", "SaleDate");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PaymentId,SaleId,PaymentTypeId,Amount,PaidAt")] Payment payment)
        {
            if (!ModelState.IsValid)
            {
                payment.PaymentId = Guid.NewGuid();
                _context.Add(payment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["PaymentTypeId"] = new SelectList(_context.PaymentTypes, "PaymentTypeId", "TypeName", payment.PaymentTypeId);
            
            ViewData["SaleId"] = new SelectList(_context.Sales, "SaleId", "SaleDate", payment.SaleId);
            
            return View(payment);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            try
            {
                var k = Guid.Parse(_keyManager.Unprotect(id));

                var payment = await _context.Payments.FindAsync(k);

                if (payment == null)
                {
                    return NotFound();
                }

                ViewData["PaymentTypeId"] = new SelectList(_context.PaymentTypes, "PaymentTypeId", "TypeName", payment.PaymentTypeId);

                ViewData["SaleId"] = new SelectList(_context.Sales, "SaleId", "SaleDate", payment.SaleId);

                return View(payment);
            }
            catch (Exception ex) 
            {
                return NotFound(ex.Message);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("PaymentId,SaleId,PaymentTypeId,Amount,PaidAt")] Payment payment)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(payment);
                    
                    await _context.SaveChangesAsync();
                    
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaymentExists(payment.PaymentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            
            ViewData["PaymentTypeId"] = new SelectList(_context.PaymentTypes, "PaymentTypeId", "TypeName", payment.PaymentTypeId);
            
            ViewData["SaleId"] = new SelectList(_context.Sales, "SaleId", "SaleDate", payment.SaleId);
            
            return View(payment);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            try
            {
                var k = Guid.Parse(_keyManager.Unprotect(id));

                var payment = await _context.Payments
                    .Include(p => p.PaymentType)
                    .Include(p => p.Sale)
                    .FirstOrDefaultAsync(m => m.PaymentId == k);

                if (payment == null)
                {
                    return NotFound();
                }

                return View(payment);
            }
            catch (Exception) 
            {
                return NotFound();
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            try
            {
                var k = Guid.Parse(_keyManager.Unprotect(id));

                var payment = await _context.Payments.FindAsync(k);

                if (payment != null)
                {
                    _context.Payments.Remove(payment);
                
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index));
            }
            catch (Exception) 
            {
                return NotFound();
            }
        }

        private bool PaymentExists(Guid id)
        {
            return _context.Payments.Any(e => e.PaymentId == id);
        }
    }
}

CashierSystem/Controllers/SalesController.cs
using CashierSystem.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CashierSystem.Controllers
{
    public class SalesController : Controller
    {
        private readonly CashierSystemContext _context;

        private readonly ApplicationDbContext _application;

        private readonly ICustomKeyManager _keyManager;

        public SalesController(CashierSystemContext context, ApplicationDbContext application,ICustomKeyManager keyManager)
        {
            _context = context;
            _application = application;
            _keyManager = keyManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var cashierSystemContext = await _context.Sales.Include(s => s.Customer).ToListAsync();

            var k = cashierSystemContext.Select(s =>
            {
                s.Id = _keyManager.Protect(s.SaleId.ToString());

                return s;

            }).ToList();

            return View(k);
        }

        public async Task<IActionResult> Details(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            try
            {

                var kk = Guid.Parse(_keyManager.Unprotect(id));

                var sale = await _context.Sales
                    .Include(s => s.Customer)
                    .FirstOrDefaultAsync(m => m.SaleId == kk);

                if (sale == null)
                {
                    return NotFound();
                }

                var cashierSystemContext = await _context.Sales.Include(s => s.Customer).ToListAsync();

                var k = cashierSystemContext.Select(s =>
                {
                    s.Id = _keyManager.Protect(s.SaleId.ToString());

                    return s;

                }).ToList();

                return View(sale);
            }
            catch (Exception) 
            {
                return NotFound();
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewData["Message"] = new SelectList(_application.MyUsers, "Id", "UserName");
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "FullName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SaleId,CustomerId,UserId,SaleDate,TotalAmount,Discount,NetAmount")] Sale sale)
        {
            if (!ModelState.IsValid)
            {
                sale.SaleId = Guid.NewGuid();
                _context.Add(sale);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["Message"] = new SelectList(_application.MyUsers, "Id", "UserName",sale.UserId);
            
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "FullName", sale.CustomerId);
            
            return View(sale);
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            try
            {
                var k = Guid.Parse(_keyManager.Unprotect(id));

                var sale = await _context.Sales.FindAsync(k);

                if (sale == null)
                {
                    return NotFound();
                }
                ViewData["Message"] = new SelectList(_application.MyUsers, "Id", "UserName", sale.UserId);
                ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "FullName", sale.CustomerId);
                return View(sale);
            }
            catch (Exception) 
            {
                return BadRequest();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("SaleId,CustomerId,UserId,SaleDate,TotalAmount,Discount,NetAmount")] Sale sale)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(sale);
                    
                    await _context.SaveChangesAsync();
                    
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SaleExists(sale.SaleId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            
            ViewData["Message"] = new SelectList(_application.MyUsers, "Id", "UserName", sale.UserId);
            
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "FullName", sale.CustomerId);
            
            return View(sale);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            try
            {
                var k = Guid.Parse(_keyManager.Unprotect(id));

                var sale = await _context.Sales
                    .Include(s => s.Customer)
                    .FirstOrDefaultAsync(m => m.SaleId == k);

                if (sale == null)
                {
                    return NotFound();
                }

                return View(sale);
            }
            catch (Exception) 
            {
                return NotFound();
            }
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            try
            {
                var k = Guid.Parse(_keyManager.Unprotect(id));

                var sale = await _context.Sales.FindAsync(k);

                if (sale != null)
                {
                    _context.Sales.Remove(sale);

                    await _context.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index));
            }
            catch (Exception) 
            {
                return NotFound();
            }
        }

        private bool SaleExists(Guid id)
        {
            return _context.Sales.Any(e => e.SaleId == id);
        }
    }
}

CashierSystem/Views/Shared/Categories & Products.cshtml
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">Inventory</a>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" asp-controller="Categories" asp-action="Index">Categories</a></li>
        <li><a class="dropdown-item" asp-controller="Products" asp-action="Index">Products</a></li>
    </ul>
</li>

CashierSystem/Views/Shared/Customers & Suppliers.cshtml
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">Business</a>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" asp-action="Index" asp-controller="Customers">Customers</a></li>
        <li><a class="dropdown-item" asp-action="Index" asp-controller="Suppliers">Suppliers</a></li>
    </ul>
</li>

CashierSystem/Views/Shared/Payments.cshtml
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">Payments</a>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" asp-controller="Payments" asp-action="Index">Payments</a></li>
        <li><a class="dropdown-item" asp-controller="PaymentTypes" asp-action="Index">Payment Types</a></li>

    </ul>
</li>

CashierSystem/Views/Shared/Report.cshtml
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">Management</a>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" asp-controller="Categories" asp-action="Index">Categories</a></li>
        <li><a class="dropdown-item" asp-controller="VwSalesDetails" asp-action="Index">Sales Details</a></li>
        <li><a class="dropdown-item" asp-controller="VwPayments" asp-action="Index">Payments</a></li>        
        <li><a class="dropdown-item" asp-controller="VwCustomerSummaries" asp-action="Index">Customer Summaries</a></li>
        <li><a class="dropdown-item" asp-controller="VwCurrentStocks" asp-action="Index">Current Stocks</a></li>
    </ul>
</li>

CashierSystem/Views/Shared/Sales.cshtml
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">Sales</a>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" asp-controller="Sales" asp-action="Index">Sales </a></li>
        <li><a class="dropdown-item" asp-controller="SaleDetails" asp-action="Index">Sales Details</a></li>
    </ul>
</li>

CashierSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.3/angular.min.js"></script>
    <title>@ViewData["Title"] - CashierSystem</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CashierSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <style>
        body {
            background-image: url("@Url.Content("~/IMG/pexels-bruna-fossile-183845208-28469559.jpg")");
            background-repeat: repeat-x;
            background-size: cover;
            background-position: center;
        }
    </style>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CashierSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StockTransactions" asp-action="Index">Stock Transactions </a>
                        </li>
                        @await Html.PartialAsync("Payments")
                        @await Html.PartialAsync("Sales")
                        @await Html.PartialAsync("Customers & Suppliers")
                        @await Html.PartialAsync("Categories & Products")
                        @await Html.PartialAsync("Report")
                    </ul>
                </div>
            </div>
            @await Html.PartialAsync("_Login")
        </nav>
    </header>
    <div  class="container bg-transparent">
        <div class="card">
            <div class="card-body bg-light-subtle">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>

    <footer class="border-top bg-light-subtle footer text-muted">
        <div class="container">
            &copy; 2025 - CashierSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CashierSystem/Views/Shared/_Login.cshtml
<div class="d-flex  align-items-center">
    @if (User.Identity.IsAuthenticated)
    {
        <div class="dropdown me-3 navbar-brand flex-wrap">
            <button class="btn dropdown-toggle px-3 py-2 fw-bold shadow-sm w-auto text-truncate" type="button" id="userDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                @using Microsoft.AspNetCore.Identity
            @inject SignInManager<MyUser> SignInManager
            @inject UserManager<MyUser> UserManager

            @if (SignInManager.IsSignedIn(User))
                {
                    var user = await UserManager.GetUserAsync(User);
                    var imagePath = user?.ImagePath;

                    if (imagePath != null && imagePath.Length > 0)
                    {
                        var base64Image = Convert.ToBase64String(imagePath);
                        <img src="data:image/jpeg;base64,@base64Image" width="115" height="65" class="rounded-pill img-fluid me-2" alt="User Image" />
                    }
                    else
                    {
                        <i class="fa-solid fa-user-circle fa-2x"></i>
                    }
                }


            </button>
            <ul class="dropdown-menu dropdown-menu-end border-0 rounded-3 w-auto" aria-labelledby="userDropdown">
                <li>
                    <a class="dropdown-item text-wrap" asp-controller="Accounts" asp-action="Profile">
                        <i class="fa-solid fa-circle-user"></i> Profile
                    </a>
                </li>
                @if (User.IsInRole("Admin"))
                {
                    <li>
                        <a class="dropdown-item text-wrap" asp-controller="ManageRoles" asp-action="Index">
                            <i class="fa-solid fa-key"></i> Role 
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item text-wrap" asp-controller="Accounts" asp-action="Index">
                            <i class="fa-solid fa-users-cog"></i> Accounts
                        </a>
                    </li>
                }
            </ul>
        </div>
        <a class="btn btn-success text-wrap" asp-controller="Accounts" asp-action="Logout">
            <i class="fa-solid fa-right-from-bracket"></i> Logout
        </a>
    }
    else
    {
        <a class="btn btn-success me-2 text-wrap" asp-controller="Accounts" asp-action="Login">
            <i class="fa-solid fa-sign-in-alt"></i> Login
        </a>
        <a class="btn btn-primary me-2 text-wrap" asp-controller="Accounts" asp-action="Register">
            <i class="fa-solid fa-user-plus"></i> Register
        </a>
    }
</div>

        <style>
    .navbar-nav .nav-link {
        transition: all 0.2s ease-in-out;
        border-radius: 6px;
        padding: 0.5rem 0.9rem;
    }

        .navbar-nav .nav-link:hover {
            background-color: #f8f9fa;
            transform: translateY(-2px);
        }

    /* Dropdown animation */
    .dropdown-menu {
        border-radius: 10px;
        transition: all 0.3s ease;
    }

    .dropdown-item:hover {
        background-color: #f1f1f1;
        transform: translateX(4px);
    }

    /* تمييز اللوجو */
    .navbar-brand img {
        transition: transform 0.3s;
    }

    .navbar-brand:hover img {
        transform: rotate(-5deg) scale(1.05);
    }

        </style>